### ISSUE TITLE
Error on running application from Australia 🦘

### ISSUE THREAD

**Issue by jipi-dev** [sanchezmarcos/binance-p2p-bot#1]
Hi, i'm trying to quote BTC to AUD and the app throws this error when processing results

```
3️⃣  Processed results
(node:17188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLocaleString' of undefined
    at /Users/<my-name>/.npm/_npx/17188/lib/node_modules/binance-p2p-bot/index.js:56:69
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:17188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce:**

1️⃣  execute `npx binance-p2p-bot`

2️⃣  Select: 
  - crypto BTC
  - fiat AUD
  - operation Buy

3️⃣  Wait for it

_Hooroo_

<img src="https://blog.lingoda.com/wp-content/uploads/2020/10/Guia-de-ingles-australiano-1.jpg" alt="cangaroos" />

**Comment by sanchezmarcos** [comment]
Thanks for reporting it!

-------

Fixed on commit: https://github.com/sanchezmarcos/binance-p2p-bot/commit/498aca2f74edb0697ebb3dcf4044f1b70c7567ea
