### ISSUE TITLE
bot p2p

### ISSUE THREAD

**Issue by jalonsos1** [sanchezmarcos/binance-p2p-bot#11]
hola esta excelente lo que hiciste
me gustaria aprender de ti si es posible, y probar binancio, se ve interesante, tambien quisiera apoyarte por eth mi correo es trombonjas@gmail.com y celular +573233093368

**Comment by sanchezmarcos** [comment]
Buen día @jalonsos1, en lo que creas que pueda ayudarte u orientarte, solo dime. 
Muchas gracias por el feedback y el apoyo al proyecto! 

Te comparto la wallet de Binancio:
```
0xaA48b4238C0fF0112977395B247C0341acB8809F
```
