### ISSUE TITLE
Bug with Bank Transfer

### ISSUE THREAD

**Issue by 5eeT0uc4** [sanchezmarcos/binance-p2p-bot#14]
Hello see the picture with error

<img width="558" alt="Screenshot 2022-04-12 at 15 25 36" src="https://user-images.githubusercontent.com/42545892/162915975-69432ade-34b8-4837-b224-e283d11531e2.png">

**Comment by 5eeT0uc4** [comment]
One more error

<img width="569" alt="Screenshot 2022-04-12 at 15 42 06" src="https://user-images.githubusercontent.com/42545892/162919331-8cdc65ff-bbe9-4cf3-ba2f-0fac3018ae0c.png">

**Comment by sanchezmarcos** [comment]
Good morning, thanks for the feedback! It seems that the error occurs with node 17 and that we do not contemplate the possibility that there are no results in the search, we will release a patch soon.

**Comment by vghulyan** [comment]
@sanchezmarcos Good work. 
I've checked your code and noticed your totalPages returns 0, hence it can not create a new Array(-1).fill(null).
I've replaced your code locally interview.js - line 49 - from:
const pagesToRun = new Array(totalPages - 1).fill(null);
to: 
const pagesToRun = new Array(totalPages === 0 ? 0 : totalPages - 1).fill(null);
and the error disappears. 
And for the second error is related to the same: the totalPrices are empty - totalPrices[minimun] (no harms but there is a spelling mistake, it's minimum not minimun) is undefined, hence it throws the error.
A simple if condition fixes the issue but not logs show.
if(totalPrices.length > 0) {...}
This is just fixing the issues, not fully debugging or finding the solution.

**Comment by vghulyan** [comment]
@sanchezmarcos Please include the thanks in fetchP2PData.js
const thanks = require("../thanks.js");

**Comment by elzorrorebelde** [comment]
this may be fixed now in https://github.com/sanchezmarcos/binancio/pull/18

can you check @5eeT0uc4?

**Comment by sanchezmarcos** [comment]
I close the issue due to inactivity and because it is resolved in the latest version.
Thank you!
