### ISSUE TITLE
Use Binance p2p API to buy/sell programmatically

### ISSUE THREAD

**Issue by nerzhul250** [sanchezmarcos/binance-p2p-bot#19]
**Is your feature request related to a problem? Please describe.**
I've been looking for a way to buy/sell crypto using Binance p2p API (programmatically).
Wondering if you know someone working on it or if you are interested in coding it.

**Describe the solution you'd like**
For instance, an sdk that allows for setting up the Binance account taking the orders on the p2p market.
Fetches available orders (you already do this)
Fetch pending orders (get endpoint)
Fetch completed orders (get endpoint)
Takes orders (post buy/sell endpoint)
Fetches chat messages with merchant (get endpoint)
Send message to merchant in order (post endpoint)
Completes orders (release/payment completed post endpoints)

**Describe alternatives you've considered**
Headless browser?
Keep using the Binance internal API (like you did)

**Comment by sanchezmarcos** [comment]
Hi @nerzhul250! For this type of use I highly recommend Puppeteer or any similar alternative.

The real problem in automating it with headless browser is that all the flows depend on not changing anything in the client UI. 

If you do so, I recommend that you write tests to validate that everything is still in place and running before executing commands using $.

https://github.com/puppeteer/puppeteer

**Comment by nerzhul250** [comment]
What do you think of using the binance internal API, what are the trade offs, challenges?

**Comment by sanchezmarcos** [comment]
Once the end-to-end flow is clear to you, the biggest challenge (and risk) of using the internal API for money transactions is that you don't find out about changes or the small implications of those changes because they are not public. 

I would definitely integrate validations to make sure nothing has changed if the bot would work on a regular frequency.
