### ISSUE TITLE
Cannot load quotes

### ISSUE THREAD

**Issue by tina80lvl** [sanchezmarcos/binance-p2p-bot#21]
⌥ I have a few questions
? Select cryptocurrency: USDT
? Select fiat currency: RUB
? Select exchange type: BUY
? Select payment method: Tinkoff
 
⌥ Collecting data for you
🔍  Fetching page 1 

/Users/tina/.npm/_npx/ed6b2388c00496ac/node_modules/binancio/src/interview.js:49
    const pagesToRun = new Array(totalPages - 1).fill(null);
                       ^

RangeError: Invalid array length
    at interview (/Users/tina/.npm/_npx/ed6b2388c00496ac/node_modules/binancio/src/interview.js:49:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by sanchezmarcos** [comment]
Sorry for the delay, I was sure I answered. What version of node.js are you using?
