### ISSUE TITLE
Bad output

### ISSUE THREAD

**Issue by cxrod** [sanchezmarcos/binance-p2p-bot#5]
Hi, I just found this great tool and test it checking the sell price of USDT in ARS but it return an odd result with max price lower  than the minimun.

`⌥ Collecting data for you
🔍  Fetching page 10/10
🔗  Transaction type USDT @ ARS
💰  193 People offering

⌥ Here I have the results
📉  Minimun price 💵  179
📊  Median price  💵  ✨ 170✨
📈  Maximun price 💵  60`

**Comment by sanchezmarcos** [comment]
Hi @cxrod! 
I just checked and you are right, it happens with the sale price but not with the purchase price. I can imagine what the source of the error must be and I will try to fix it on the weekend.

Thank you very much for the feedback!

**Comment by sanchezmarcos** [comment]
Fixed! 👌
