### ISSUE TITLE
No decimal value! how can i get the full price information ?

### ISSUE THREAD

**Issue by kbrall** [sanchezmarcos/binance-p2p-bot#7]
Hi, i realy loved your work, im having a little problem, im trying to get the quotations USDT/BRL, and the prices only comes with no decimal value! like... Low 5, medium 5, high 6. How can i get the full price with the cents ? 

sorry for being a noob in coding!

thanks

**Comment by kbrall** [comment]
I have a few questions
? Select cryptocurrency: USDT
? Select fiat currency: BRL
? Select exchange type: BUY

⌥ Collecting data for you
🔍  Fetching page 3/3
🔗  Transaction type USDT @ BRL
💰  55 People offering

⌥ Here I have the results
📉  Minimun price 💵  5
📊  Median price  💵  ✨ 5✨
📈  Maximun price 💵  6

**Comment by sanchezmarcos** [comment]
Good morning, I will check the problem you mention about the decimals. Thank you very much for the feedback!

**Comment by sanchezmarcos** [comment]
The new release #9 has already fixed this problem by @redet-G  🎉 it's updated on NPM, you can try it!
